# -*- coding: utf-8 -*-
"""RangeAddition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ps0qXrL9hwmY0Sqki4vUIZLG4pXi5kbb
"""

def add(arr, N, lo, hi, val): 

	arr[lo] += val 
	if (hi != N - 1): 
		arr[hi + 1] -= val 
def updateArray(arr, N): 
	for i in range(1, N): 
		arr[i] += arr[i - 1] 

def printArr(arr, N): 
	updateArray(arr, N)
	return arr 

for _ in range(int(input())):
  N = int(input())
  c=list(map(int,input().split()))
  h=list(map(int,input().split()))
  arr= [0 for i in range(N)]

  for i in range(N):
    lb=i-c[i]
    ub=i+c[i]
    if ub>=N-1:
      ub=N-1
    if lb<=0:
      lb=0
    add(arr,N,lb,ub,1)
  r=printArr(arr, N) 
  if sorted(r)==sorted(h):
    print('YES')
  else:
    print('NO')

3 4 5 2 4